"""Seed data for the jargon glossary."""

SEED_DATA = [
    # Makes
    {"abbreviation": "FRL", "expansion": "Freightliner", "category": "make"},
    {"abbreviation": "PB", "expansion": "Peterbilt", "category": "make"},
    {"abbreviation": "Pete", "expansion": "Peterbilt", "category": "make"},
    {"abbreviation": "KW", "expansion": "Kenworth", "category": "make"},
    {"abbreviation": "INT", "expansion": "International", "category": "make"},
    {"abbreviation": "Navistar", "expansion": "International", "category": "make"},
    {"abbreviation": "MACK", "expansion": "Mack Trucks", "category": "make"},
    {"abbreviation": "WS", "expansion": "Western Star", "category": "make"},
    {"abbreviation": "HYND", "expansion": "Hyundai Translead", "category": "make"},
    {"abbreviation": "UTIL", "expansion": "Utility Trailer", "category": "make"},
    {"abbreviation": "GDN", "expansion": "Great Dane", "category": "make"},
    {"abbreviation": "WBSH", "expansion": "Wabash", "category": "make"},
    {"abbreviation": "STGH", "expansion": "Stoughton", "category": "make"},
    {"abbreviation": "VANG", "expansion": "Vanguard", "category": "make"},
    {"abbreviation": "HINO", "expansion": "Hino", "category": "make"},

    # Models
    {"abbreviation": "Casc", "expansion": "Cascadia", "category": "model"},
    {"abbreviation": "T680", "expansion": "Kenworth T680", "category": "model"},
    {"abbreviation": "T880", "expansion": "Kenworth T880", "category": "model"},
    {"abbreviation": "W900", "expansion": "Kenworth W900", "category": "model"},
    {"abbreviation": "579", "expansion": "Peterbilt 579", "category": "model"},
    {"abbreviation": "389", "expansion": "Peterbilt 389", "category": "model"},
    {"abbreviation": "VNL", "expansion": "Volvo VNL", "category": "model"},
    {"abbreviation": "VNR", "expansion": "Volvo VNR", "category": "model"},
    {"abbreviation": "LT", "expansion": "International LT", "category": "model"},
    {"abbreviation": "Prostar", "expansion": "International ProStar", "category": "model"},
    {"abbreviation": "Anthem", "expansion": "Mack Anthem", "category": "model"},
    {"abbreviation": "Pinnacle", "expansion": "Mack Pinnacle", "category": "model"},

    # Engines
    {"abbreviation": "DD13", "expansion": "Detroit Diesel DD13", "category": "engine"},
    {"abbreviation": "DD15", "expansion": "Detroit Diesel DD15", "category": "engine"},
    {"abbreviation": "DD16", "expansion": "Detroit Diesel DD16", "category": "engine"},
    {"abbreviation": "X15", "expansion": "Cummins X15", "category": "engine"},
    {"abbreviation": "X12", "expansion": "Cummins X12", "category": "engine"},
    {"abbreviation": "ISX", "expansion": "Cummins ISX", "category": "engine"},
    {"abbreviation": "ISX15", "expansion": "Cummins ISX15", "category": "engine"},
    {"abbreviation": "MX-13", "expansion": "Paccar MX-13", "category": "engine"},
    {"abbreviation": "MX13", "expansion": "Paccar MX-13", "category": "engine"},
    {"abbreviation": "D13", "expansion": "Volvo D13", "category": "engine"},
    {"abbreviation": "MP8", "expansion": "Mack MP8", "category": "engine"},
    {"abbreviation": "N13", "expansion": "Navistar N13", "category": "engine"},

    # Vehicle types
    {"abbreviation": "reefer", "expansion": "refrigerated trailer", "category": "vehicle_type"},
    {"abbreviation": "flatbed", "expansion": "flatbed trailer", "category": "vehicle_type"},
    {"abbreviation": "stepdeck", "expansion": "step deck trailer", "category": "vehicle_type"},
    {"abbreviation": "dry van", "expansion": "dry van trailer", "category": "vehicle_type"},
    {"abbreviation": "tanker", "expansion": "tanker trailer", "category": "vehicle_type"},
    {"abbreviation": "lowboy", "expansion": "lowboy trailer", "category": "vehicle_type"},
    {"abbreviation": "hotshot", "expansion": "hotshot trailer", "category": "vehicle_type"},
    {"abbreviation": "conestoga", "expansion": "conestoga trailer", "category": "vehicle_type"},
    {"abbreviation": "daycab", "expansion": "day cab tractor", "category": "vehicle_type"},
    {"abbreviation": "sleeper", "expansion": "sleeper cab tractor", "category": "vehicle_type"},
    {"abbreviation": "bobtail", "expansion": "truck without trailer", "category": "vehicle_type"},
    {"abbreviation": "B-train", "expansion": "B-train double trailer", "category": "vehicle_type"},

    # Conditions and terms
    {"abbreviation": "DOT", "expansion": "Department of Transportation", "category": "general"},
    {"abbreviation": "APU", "expansion": "auxiliary power unit", "category": "general"},
    {"abbreviation": "DPF", "expansion": "diesel particulate filter", "category": "general"},
    {"abbreviation": "DEF", "expansion": "diesel exhaust fluid", "category": "general"},
    {"abbreviation": "EGR", "expansion": "exhaust gas recirculation", "category": "general"},
    {"abbreviation": "SCR", "expansion": "selective catalytic reduction", "category": "general"},
    {"abbreviation": "OTR", "expansion": "over the road", "category": "general"},
    {"abbreviation": "CDL", "expansion": "commercial driver's license", "category": "general"},
    {"abbreviation": "GVWR", "expansion": "gross vehicle weight rating", "category": "general"},
    {"abbreviation": "GCW", "expansion": "gross combination weight", "category": "general"},
    {"abbreviation": "WB", "expansion": "wheelbase", "category": "general"},
    {"abbreviation": "TA", "expansion": "tandem axle", "category": "general"},
    {"abbreviation": "SA", "expansion": "single axle", "category": "general"},
    {"abbreviation": "ELD", "expansion": "electronic logging device", "category": "general"},
    {"abbreviation": "PM", "expansion": "preventive maintenance", "category": "general"},
    {"abbreviation": "DOC", "expansion": "diesel oxidation catalyst", "category": "general"},
    {"abbreviation": "VIN", "expansion": "vehicle identification number", "category": "general"},
    {"abbreviation": "ECM", "expansion": "engine control module", "category": "general"},
    {"abbreviation": "CARB", "expansion": "California Air Resources Board", "category": "general"},
    {"abbreviation": "EPA", "expansion": "Environmental Protection Agency", "category": "general"},
    {"abbreviation": "OBO", "expansion": "or best offer", "category": "general"},

    # Units
    {"abbreviation": "K", "expansion": "thousand (miles or dollars)", "category": "unit"},
    {"abbreviation": "mi", "expansion": "miles", "category": "unit"},
]
